### ISSUE TITLE
Slash Command - Class Role Management

### ISSUE THREAD

**Issue by gmacgre** [BYU-CS-Discord/CSBot#12]
The bot can add and remove roles from users. Only roles that are registered can be managed by the bot.

`/register-role <role-name> [complete-name]`: registers a role so the bot can manager it. Names are used instead of ids for convenience (if there are two with the same name, throw an error). Providing a [complete-name] argument pairs the two roles together for use in the `complete` command. 
- Can take a flag: `/register-role -complete=<complete-name>` for roles that _only_ have a complete version (such as `dating complete`)

`/list-roles`: self explanatory. Format in a way that makes it clear which roles are paired.

`/add-roles <role-name[, <role-name>...]>`: the argument is a comma separated list of role names. This will add all of the registered roles to the user, and tell them if it was unable to add any roles since they're not registered under that name.

`/remove-roles <role-name[, <role-name>...]>`: Inverse of `add-roles`

`/complete <role-name[, <role-name>...]>`: removes <role-name> and adds it's "complete" variant. Fails for a role if there is no complete variant. `dating` should still work as an argument.

`add-role` and `remove-role` are aliases of `add-roles` and `remove-roles` respectively.

**Comment by Plyb** [comment]
Right now, Ze Kaiser can add or remove any role that is lower than his own. In the future, I'd like to be able to specify which roles he can modify specifically (so that non-bot-modifiable roles can be lower than class roles for instance, something we've wanted in the past but can't do right now). I'm not sure if this is best done with an allow-list or a block-list, but one of the two.

Change number two is that rn Ze Kaiser just treats any role with "complete" in its name as the counterpart to the one that is just the prefix (which is what leads to the humorous behavior that `!complete dating` works). It might be good to have some way to explicitly bind them together so we're not just relying on role names.

**Comment by gmacgre** [comment]
Multiple times there have been people that have had issues on the addrole-addroles mixup in determining how to add their roles. Should we simply it to simply either `addroles`?

**Comment by Plyb** [comment]
That is why I have `addrole` just being an alias for `addroles`. It's simpler for development, and if the two do the same thing, I think there will be less confusion

**Comment by ZYancey** [comment]
I know we want to bring it up to parity with Ze Kaiser first but would it make sense for class role selection to use buttons or dropdowns or something that is a little more user friendly than the current Ze kaiser implementation? Needing to guess which roles exist and then getting the command correct is a big hurdle for new users. I think it could be worth doing at the same time as this PR rather than bringing in the clunky previous solution with its current flaws
Just a thought.

**Comment by AverageHelper** [comment]
Yeah. A dropdown menu would be nice if that's available to us. I think discord.js has APIs to grab the existing roles, and those can be made configurable too. Discord also has ways to [generate select menus dynamically](https://discordjs.guide/interactions/select-menus.html#building-and-sending-select-menus), tho they would require more than one interaction.

**Comment by Plyb** [comment]
Closing because this feature is obviated by the channel browser
