### ISSUE TITLE
Add the GitHub repo link to the /help command

### ISSUE THREAD

**Issue by JstnMcBrd** [BYU-CS-Discord/CSBot#30]
... and replace the user activity with something else.

**Comment by AverageHelper** [comment]
I think having the URL within easy reach might be nice for various commands. A future `/info` command, for example, like was mentioned in the Discord. I think putting this info in the command context might be useful. But since that info doesn't ever change, perhaps a folder dedicated to importable constants might be a better way to go.

I'm procrastinating sleep, so I'll get started on this tonight!

**Comment by AverageHelper** [comment]
See #31
