### ISSUE TITLE
Slash Command - Is CAS down?

### ISSUE THREAD

**Issue by JstnMcBrd** [BYU-CS-Discord/CSBot#74]
`/is-cas-down`
See this [Discord thread](https://discord.com/channels/341633933894746122/1085760745595228270).

Would ping `cas.byu.edu` and respond if CAS is down.

Perhaps use [ping](https://www.npmjs.com/package/ping) node module?

**Comment by josephgeis** [comment]
I don't think pinging `cas.byu.edu` would necessarily tell us if it is down because the underlying CAS app (which is behind a reverse proxy) could simply be down, which would cause requests to verify tickets to fail while the server is still online.

Perhaps sending an empty GET request to `https://cas.byu.edu/cas/serviceValidate` and checking it isn't a 502/504.

**Comment by josephgeis** [comment]
Learned the other day that there is a status dashboard on OIT's website. https://it.byu.edu/it?id=services_status
